config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    path: '/admin',
    registrations: 'admin/admins/registrations',
    sessions: 'admin/admins/sessions',
    passwords: 'admin/admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'public/users/sessions',
    passwords: 'public/users/passwords',
    registrations: 'public/users/registrations'
  }

  # Helperにadminをつけるためnamespaceを使う
  namespace  :admin do
    root to: 'homes#top'
    get 'admin/recipes', to: 'searches#index'
    get 'admin/searches', to: 'searches#search'
    resources :users, except: %i[create new destroy]
    resources :genres
    resources :recipes, only: %i[index show destroy] do
      collection do
        get 'genre_chart'
        get 'week_chart'
      end
      resources :reviews, only: %i[index destroy]
    end
    resources :contacts do
      member do
        patch 'status'
      end
    end
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about', to: 'homes#about'
    resources :contacts, only: %i[new create] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :recipes do
      member do 
        patch 'serving_update'
      end
      collection do
        get 'search'
        get 'ranking'
        get 'pv_ranking'
        get 'raty_ranking'
        get 'genre_ranking'
      end
      resources :bookmarks, only: %i[create destroy]
      resources :reviews, only: %i[create destroy index show]
      member do
        get 'recipe/genres', to: 'recipes#genre'
      end
    end
    resources :procedures, only: %i[new create]
    resources :users, only: [:update] do
      resource :relationships, only: %i[create destroy]
    end
    get 'my_page' => 'users#show'
    get 'my_page/edit' => 'users#edit'
    get 'my_page/cancel', to: 'users#cancel'
    patch 'my_page/unsubscribe', to: 'users#unsubscribe'
    get 'recipes', to: 'searches#index'
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @recipes = Recipe.all
  end
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 m-auto m-4 d-flex flex-wrap p-5 text-center">
      <h2 class="col-6 mb-5"><%= link_to "お問い合わせ一覧", admin_contacts_path, class: "text-dark"  %></h2>
      <h2 class="col-6 mb-5"><%= link_to "レシピ一覧", admin_recipes_path, class: "text-dark" %></h2>
      <h2 class="col-6 mb-5"><%= link_to "会員一覧", admin_users_path, class: "text-dark" %></h2>
      <h2 class="col-6 mb-5"><%= link_to "ジャンル一覧", admin_genres_path, class: "text-dark" %></h2>
      <h2 class="col-6 mb-5"><%= link_to "ジャンル別投稿数", genre_chart_admin_recipes_path, class: "text-dark" %></h2>
      <h2 class="col-6 mb-5"><%= link_to "前日/先週/先月比", week_chart_admin_recipes_path, class: "text-dark" %></h2>
      <h2 class="col-6 mt-5"><%= link_to "ログイン ➡︎", new_admin_session_path, class: "text-dark" %></h2>
    </div>
  </div>
</div>