config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    path: '/admin',
    registrations: 'admin/admins/registrations',
    sessions: 'admin/admins/sessions',
    passwords: 'admin/admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'public/users/sessions',
    passwords: 'public/users/passwords',
    registrations: 'public/users/registrations'
  }

  # Helperにadminをつけるためnamespaceを使う
  namespace  :admin do
    root to: 'homes#top'
    get 'admin/recipes', to: 'searches#index'
    get 'admin/searches', to: 'searches#search'
    resources :users, except: %i[create new destroy]
    resources :genres
    resources :recipes, only: %i[index show destroy] do
      collection do
        get 'genre_chart'
        get 'week_chart'
      end
      resources :reviews, only: %i[index destroy]
    end
    resources :contacts do
      member do
        patch 'status'
      end
    end
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about', to: 'homes#about'
    resources :contacts, only: %i[new create] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :recipes do
      member do 
        patch 'serving_update'
      end
      collection do
        get 'search'
        get 'ranking'
        get 'pv_ranking'
        get 'raty_ranking'
        get 'genre_ranking'
      end
      resources :bookmarks, only: %i[create destroy]
      resources :reviews, only: %i[create destroy index show]
      member do
        get 'recipe/genres', to: 'recipes#genre'
      end
    end
    resources :procedures, only: %i[new create]
    resources :users, only: [:update] do
      resource :relationships, only: %i[create destroy]
    end
    get 'my_page' => 'users#show'
    get 'my_page/edit' => 'users#edit'
    get 'my_page/cancel', to: 'users#cancel'
    patch 'my_page/unsubscribe', to: 'users#unsubscribe'
    get 'recipes', to: 'searches#index'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes,	dependent: :destroy
  has_many :bookmarks,	dependent: :destroy
  has_many :reviews,	dependent: :destroy
  has_many :reverse_of_relationships,	class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed
  has_many :contacts, dependent: :destroy

  with_options presence: true do
    validates :name

    validates :email
    validates :password, on: :create # 新規登録するときにのみバリデーションによる入力チェックがかかるように変更
  end

  validates :introduction, length: { maximum: 150 }

  # superで渡された引数を親クラスに受け渡しできる

  def active_for_authentication?
    super && (is_deleted == false)
  end

  # フォロー機能のメソッド

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update!(user_params)
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

  def withdrawl
    @user = User.find(params[:id])
    if @user.update(is_deleted: true)
      reset_session     # データをリセットする
      flash[:notice] = 'ユーザーを退会させました'
      redirect_to admin_users_path
    else
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:is_deleted)
  end
end

app/views/admin/users/edit.html.erb
<div class="container">
  <h3 class="m-5">会員ステータスの変更</h3>
    <div class="row">
      <div class="col-10 m-auto">
      <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch, local:true do |f| %>
      <table class="table small">
        <tr>
          <td>ユーザー名</td>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <td>自己紹介</td>
          <td><%= @user.introduction %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td>
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "有効" %><br />
            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, "退会" %>
          </td>
        </tr>
      </table>

      <div class="d-flex mt-4 ml-2">
        <%= f.submit:'会員ステータスを変更', class:'btn btn-sm btn-primary py-0', data:
        { confirm: "ステータスを変更しますか？",
            cancel: 'キャンセル',
            commit: '変更'}, title: '変更の確認' %>
        <%= link_to "戻る", admin_user_path(@user.id), class: 'btn btn-sm btn-secondary ml-4' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <h2 class="m-5">会員一覧</h2>
  <div class="row">
    <div class="col-10 m-auto m-4">
      <table class="table small table-hover m-4">
        <thead>
            <tr>
              <th>会員ID</th>
              <th>会員名</th>
              <th>イントロダクション</th>
              <th>ステータス</th>
              <th></th>
            </tr>
        </thead>
        <tbody id="post">
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <td><%= user.introduction %></td>
            <% if user.is_deleted %>
              <td class="text-secondary">退会済み</td>
            <% else %>
               <td class="text-success">有効</td>
            <% end %>
            <td><%= link_to "詳細", admin_user_path(user) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <h2 class="m-5">会員詳細</h2>
  <div class="row">
    <div class="col-10 m-auto m-4">
      <table class="table small table-hover">
        <thead>
          <tr>
            <th scope="col">会員名</th>
            <th scope="col">イントロダクション</th>
            <th scope="col">メールアドレス</th>
            <th scope="col">投稿したレシピ</th>
            <th scope="col">退会ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th><%= @user.name %></th>
            <td><%= @user.introduction %></td>
            <td><%= @user.email %></td>
            <td>
              <% @user.recipes.each do |recipe| %>
                <div class="flex-column">
                  <%= link_to admin_recipe_path(recipe.id) do %>
                    <%= recipe.name %>
                  <% end %>
                </div>
              <% end %>
            </td>
              <% if @user.is_deleted %>
              <td class="text-secondary">退会済み</td>
            <% else %>
               <td class="text-success">有効</td>
            <% end %>
            <td><%= link_to "編集", edit_admin_user_path(@user) %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>