config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    path: '/admin',
    registrations: 'admin/admins/registrations',
    sessions: 'admin/admins/sessions',
    passwords: 'admin/admins/passwords'
  }

  devise_for :users, controllers: {
    sessions: 'public/users/sessions',
    passwords: 'public/users/passwords',
    registrations: 'public/users/registrations'
  }

  # Helperにadminをつけるためnamespaceを使う
  namespace  :admin do
    root to: 'homes#top'
    get 'admin/recipes', to: 'searches#index'
    get 'admin/searches', to: 'searches#search'
    resources :users, except: %i[create new destroy]
    resources :genres
    resources :recipes, only: %i[index show destroy] do
      collection do
        get 'genre_chart'
        get 'week_chart'
      end
      resources :reviews, only: %i[index destroy]
    end
    resources :contacts do
      member do
        patch 'status'
      end
    end
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about', to: 'homes#about'
    resources :contacts, only: %i[new create] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :recipes do
      member do 
        patch 'serving_update'
      end
      collection do
        get 'search'
        get 'ranking'
        get 'pv_ranking'
        get 'raty_ranking'
        get 'genre_ranking'
      end
      resources :bookmarks, only: %i[create destroy]
      resources :reviews, only: %i[create destroy index show]
      member do
        get 'recipe/genres', to: 'recipes#genre'
      end
    end
    resources :procedures, only: %i[new create]
    resources :users, only: [:update] do
      resource :relationships, only: %i[create destroy]
    end
    get 'my_page' => 'users#show'
    get 'my_page/edit' => 'users#edit'
    get 'my_page/cancel', to: 'users#cancel'
    patch 'my_page/unsubscribe', to: 'users#unsubscribe'
    get 'recipes', to: 'searches#index'
  end
end

app/views/layouts/_error_message.html.erb
<% if obj.errors.any? %>
  <ul class="error_explanation text-danger border rounded border-danger m-2">
    <%= obj.errors.count %>件のエラー
    <% obj.errors.full_messages.each do |message| %>
      <li class="text-danger small mt-1 ml-4"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
 <footer class="bg-light pt-5 pb-4 mt-auto">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <h5>ラーメンを家庭料理に</h5>
          </div>
          <div class="ml-auto">
            <h6 class="mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-dark">会社概要</a>
              </li>
              <% if user_signed_in? %>
              <li>
                <%= link_to "お問い合わせ",  new_contact_path, class: "text-dark" %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </footer>

app/views/layouts/_header.html.erb
    <header>
      <nav class="navbar navbar-expand-lg navbar-light p-4">
        <% if user_signed_in? %>
          <%= link_to root_path do %>
            <%= image_tag "2656826.jpg", size: "100x70", class: "d-none d-sm-block mr-3" %>
          <% end %>
        <% elsif admin_signed_in? %>
          <%= link_to admin_root_path do %>
            <%= image_tag '2656826.jpg', size: '100x70', class: "d-none d-sm-block mr-3"%>
          <% end %>
        <% else %>
          <%= link_to root_path do %>
            <%= image_tag '2656826.jpg', size: '100x70', class: "d-none d-sm-block mr-3"%>
          <% end %>
        <% end %>
        <div class="flex-column">
          <h1 class="">まいら〜めん</h1>
          <small class="ml-2">自分だけのオリジナルらーめんを作ろう ！</small>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item mr-3">
              <%= form_with(url: search_recipes_path, local: true, method: :get, class: "search-field") do |f| %>
                <%= f.text_field :keyword, placeholder: "レシピを検索する", class: "form-control" %>
                <%= button_tag type: 'submit', class: 'btn search-icon' do %>
                  <i class="fas fa-search"></i>
                <% end %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', my_page_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'レシピを投稿する', new_recipe_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item mr-3">
              <%= form_with(url: admin_admin_searches_path, local: true, method: :get, class: "search-field d-flex") do |f| %>
                <%= f.select :model, options_for_select({"会員" => "user", "レシピ" => "recipe"}) %>
                  <%= f.text_field :content, placeholder: "検索", class: "form-control" %>
                  <%= button_tag type: 'submit', class: 'btn search-icon' do %>
                    <i class="fas fa-search"></i>
                  <% end %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to 'お問い合わせ一覧', admin_contacts_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'レシピ一覧',  admin_recipes_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '会員一覧', admin_users_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
          <% else %>
            <li class="nav-item mr-3">
              <%= form_with(url: search_recipes_path, local: true, method: :get, class: "search-field") do |f| %>
                <%= f.text_field :keyword, placeholder: "レシピを検索する", class: "form-control" %>
                <%= button_tag type: 'submit', class: 'btn search-icon' do %>
                  <i class="fas fa-search"></i>
                <% end %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
          <% end %>
          </ul>
        </div>
      </nav>
 </header>

app/views/layouts/_sidebar.html.erb
<div class="col-lg-2 col-md-2 col-sm-12 flex-column m-4">
  <ul class="list-unstyled pt-5 border-top menu" id="global_nav">
    <li class="active mb-5"><strong>ジャンル別検索</strong>
      <% genres.each do |genre| %>
        <ul class="list-unstyled menuSub">
          <li class="active mt-5">
            <%= link_to recipe_genres_recipe_path(genre.id), class: "text-decoration-none text-dark" do %>
              <%= genre.name %>
            <% end %>
          </li>
        </ul>
    <% end %>
    </li>
    <li class="active mb-5 pt-5 border-top menu"><strong>全体ランキング</strong>
      <ul class="list-unstyled menuSub">
        <li class="active mt-5"><%= link_to "評価の高いレシピ", raty_ranking_recipes_path, class: "text-decoration-none text-dark" %></li>
        <li class="active mt-5"><%= link_to "ブックマークの多いレシピ", ranking_recipes_path, class: "text-decoration-none text-dark" %></li>
        <li class="active mt-5"><%= link_to "プレビューの多いレシピ", pv_ranking_recipes_path, class: "text-decoration-none text-dark" %></li>
      </ul>
    </li>
    <li class="active mb-5 pt-5 border-top menu"><strong>ジャンル別ランキング(レビュー順)</strong>
      <% @genres.each do |genre| %>
      <ul>
        <li class="active mt-5 menuSub">
            <%= link_to  genre_ranking_recipes_path(genre_id: genre.id), class: "text-decoration-none text-dark" do %>
              <% genre.name %>
            <% end %>
        </li>
      </ul>
    <% end %>
    </li>
  </ul>
</div>


<script>

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>らーめんレシピサイト</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <%= favicon_link_tag('favicon.ico') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@500;600;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag   'application', media: 'all' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
      <main class="mb-auto">
        <p class="notice col-6 m-auto text-success"><%= notice %></p>
        <p class="alert col-6 m-auto text-danger"><%= alert %></p>
        <%= link_to "←トップページへ", root_path, class: "p-4 d-block d-sm-none text-dark" %>
        <%= yield %>
    　</main>
    <%= render 'layouts/footer' %>
  </body>
</html>